from meu_grafo import MeuGrafo

grafo_teste= MeuGrafo(['1', '2', '3', '4', '5','6', '7'])
grafo_teste.adicionaAresta('a1', '1', '2')
grafo_teste.adicionaAresta('a2', '2', '3')
grafo_teste.adicionaAresta('a3', '3', '4')
grafo_teste.adicionaAresta('a4', '5', '1')
grafo_teste.adicionaAresta('a5', '1', '3')
grafo_teste.adicionaAresta('a6', '3', '4')
grafo_teste.adicionaAresta('a7', '1', '4')
grafo_teste.adicionaAresta('a8', '3', '4')
grafo_teste.adicionaAresta('a9', '2', '4')
grafo_teste.adicionaAresta('a10', '3', '5')
grafo_teste.adicionaAresta('a11', '2', '5')
grafo_teste.adicionaAresta('a12', '6', '7')
grafo_teste.adicionaAresta('a13', '7', '2')
grafo_teste.adicionaAresta('a14', '6', '2')
print(grafo_teste.bfs("1"))
print(grafo_teste.dfs("1"))